# @name createRecharge


 POST http://localhost:3000/recharge
Content-Type: application/json

{ 
  "user_id": "12346", 
  "phone_number": "+15551234587", 
  "amount": 10.78
}


###

GET http://localhost:3000/recharge/status?user_id=12346&phone_number=+15551234587 
Content-Type: application/json
